TRUNCATE TABLE products RESTART IDENTITY CASCADE;

INSERT INTO
    products (
        name,
        price,
        category,
        description,
        image_url,
        is_available
    )
VALUES (
        'いちごかき氷',
        600,
        'かき氷本体',
        '果肉たっぷりのいちごソースをかけた定番かき氷。',
        'uploads/いちごソース.png',
        true
    ),
    (
        '宇治金時抹茶',
        750,
        'かき氷本体',
        '高級宇治抹茶と濃厚な粒あんの贅沢な味わい。',
        'uploads/宇治金時抹茶.png',
        true
    ),
    (
        'マンゴーかき氷',
        700,
        'かき氷本体',
        '濃厚でトロピカルな完熟マンゴーソースかき氷。',
        'uploads/マンゴー.png',
        true
    ),
    (
        'メロンかき氷',
        650,
        'かき氷本体',
        'フルーティーな甘さの特製メロンソースかき氷。',
        'uploads/メロンソース.png',
        true
    ),
    (
        'ブルーハワイ',
        500,
        'かき氷本体',
        'お祭り気分を味わえる爽快ブルーハワイシロップ。',
        'uploads/ブルーハワイ.png',
        true
    ),
    (
        'ピーチかき氷',
        700,
        'かき氷本体',
        '上品な甘さの国産桃ソースを使用したかき氷。',
        'uploads/桃.png',
        true
    ),
    (
        '特製わらび餅',
        400,
        'スナック',
        'ぷるぷる食感のきな粉と黒蜜のわらび餅セット。',
        'uploads/わらび餅.png',
        true
    ),
    (
        'さくらもちセット',
        450,
        'スナック',
        'ほんのり桜が香る伝統的な和菓子セット。',
        'uploads/さくらもち.png',
        true
    );